### ISSUE TITLE
Fatal error: Call to undefined function imagecreatefromstring() in /Applications/AMPPS/www/ImageCompare-master/src/Image.php on line 325

### ISSUE THREAD

**Issue by davamp** [inceddy/ImageCompare#1]

**Comment by inceddy** [comment]
ImageCompare relies on the image functions from GD-Lib. Make sure you PHP is compiled with or has enabled this extension. 

For more information see
http://php.net/manual/de/book.image.php
and for details on the mentioned function
http://php.net/manual/de/function.imagecreatefromstring.php

Check your 'php_info()' for details of your installation.
