### ISSUE TITLE
Error while comparing

### ISSUE THREAD

**Issue by nawafgantare** [inceddy/ImageCompare#2]
When i try to compare the images.this is the error i get

Fatal error: Uncaught Exception: Invalid argument for Color::fromInt. Must be an integer between 0 and 16777215 in C:\xampp\htdocs\l4l\ImageCompare\src\color.php:240 Stack trace: #0 C:\xampp\htdocs\l4l\ImageCompare\src\image.php(183): Color::fromInt(2130706432) #1 C:\xampp\htdocs\l4l\ImageCompare\src\image.php(147): Image->colorat(0, 0) #2 C:\xampp\htdocs\l4l\ImageCompare\test.php(13): Image->subtract(Object(Image), 15) #3 {main} thrown in C:\xampp\htdocs\l4l\ImageCompare\src\color.php on line 240

**Comment by inceddy** [comment]
Are you comparing png image files? My first shot is to assume RGBA color as error source, since this was not on my mind during the developemt.

**Comment by inceddy** [comment]
This issue should be fixed now.
