### ISSUE TITLE
Is Composer JSON name out of sync with GITHUB name?

### ISSUE THREAD

**Issue by 1fifoto** [inceddy/ImageCompare#8]
Using composer to access your package I get...

    Loading composer repositories with package information
    Reading composer.json of inceddy/image-compare (alpha1.1)
    Reading composer.json of inceddy/image-compare (alpha1.0)
    Reading composer.json of inceddy/image-compare (master)
    Updating dependencies (including require-dev)
    Your requirements could not be resolved to an installable set of packages.

Could this be from the fact that the "image-compare" name specified in the composer.json file does not match the github.com name of "ImageCompare"?

**Comment by inceddy** [comment]
I published ImageCompare on [packagist.org](https://packagist.org/packages/inceddy/image-compare) as version 1.0.0 

Just use:
````
{
    "require": {
        "inceddy/image-compare": "~1.0"
    }
}
````
